### ISSUE TITLE
开箱模拟器的与当前查询账号船库挂钩选项似乎没有效果

### ISSUE THREAD

**Issue by SnowMoonSS** [wows-yuyuko/wows-mgaia-vue3#10]
![image](https://github.com/user-attachments/assets/4845eea0-78b5-4c2d-beba-3e514931bebf)
船池总共145艘，然而勾上与当前查询账号船库挂钩任然出货145艘……

**Comment by missile-xuan** [comment]
不挂钩
<img width="1211" alt="image" src="https://github.com/user-attachments/assets/94773397-ac67-4b45-b627-964bab2d1142" />


挂钩
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/ef1c71cc-5820-4c12-b5a1-e67d62ee3414" />

我的号试了下正常的
那有没有可能是 这次箱子出的船你全都没有啊

**Comment by SnowMoonSS** [comment]
> 不挂钩 <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/38873815/397644636-94773397-ac67-4b45-b627-964bab2d1142.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ2MzYtOTQ3NzMzOTctYWM2Ny00YjQ1LWI2MjctOTY0YmFiMmQxMTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDkzOTRjZjY5OTM2ZGQ0NWNmYzRlMjc2OGU2ZWMzZjEzOThmMDA2MWM1NjM5OTU3ZDY2ZjNlNmMxZGRkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HNItZ-tQ0VggZaloPBbvhZYnE6fgtEwvebsvYHEn7Nw">
> 
> 挂钩 <img alt="image" width="1183" src="https://private-user-images.githubusercontent.com/38873815/397644791-ef1c71cc-5820-4c12-b5a1-e67d62ee3414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ3OTEtZWYxYzcxY2MtNTgyMC00YzEyLWI1YTEtZTY3ZDYyZWUzNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MGJhMDE3ZTMwZDlhMTZjZDMyNGRkZTY4ZjgyZjhjZDQ1Y2JhM2YzZTY4NzYyOThkMWVmYjAzMzZhNjU1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vl_gvrbY5gwMjhMdWDqo2Xm9c4N6-dMSWCT1of-KFas">
> 
> 我的号试了下正常的 那有没有可能是 这次箱子出的船你全都没有啊

我也找群友试过，似乎国服是正常的，但是亚服就不行
圣诞刚冲了100发怎么会啥都没有
![7c659d43da9a9b1e6f64d0ca83c3af08](https://github.com/user-attachments/assets/a8eb114c-a95e-4c87-af94-b766ad1513e3)

**Comment by missile-xuan** [comment]
> > 不挂钩 <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/38873815/397644636-94773397-ac67-4b45-b627-964bab2d1142.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ2MzYtOTQ3NzMzOTctYWM2Ny00YjQ1LWI2MjctOTY0YmFiMmQxMTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDkzOTRjZjY5OTM2ZGQ0NWNmYzRlMjc2OGU2ZWMzZjEzOThmMDA2MWM1NjM5OTU3ZDY2ZjNlNmMxZGRkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HNItZ-tQ0VggZaloPBbvhZYnE6fgtEwvebsvYHEn7Nw">
> > 挂钩 <img alt="image" width="1183" src="https://private-user-images.githubusercontent.com/38873815/397644791-ef1c71cc-5820-4c12-b5a1-e67d62ee3414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ3OTEtZWYxYzcxY2MtNTgyMC00YzEyLWI1YTEtZTY3ZDYyZWUzNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MGJhMDE3ZTMwZDlhMTZjZDMyNGRkZTY4ZjgyZjhjZDQ1Y2JhM2YzZTY4NzYyOThkMWVmYjAzMzZhNjU1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vl_gvrbY5gwMjhMdWDqo2Xm9c4N6-dMSWCT1of-KFas">
> > 我的号试了下正常的 那有没有可能是 这次箱子出的船你全都没有啊
> 
> 我也找群友试过，似乎国服是正常的，但是亚服就不行 圣诞刚冲了100发怎么会啥都没有 ![7c659d43da9a9b1e6f64d0ca83c3af08](https://private-user-images.githubusercontent.com/21017431/397645852-a8eb114c-a95e-4c87-af94-b766ad1513e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODM4MjYsIm5iZiI6MTczNDY4MzUyNiwicGF0aCI6Ii8yMTAxNzQzMS8zOTc2NDU4NTItYThlYjExNGMtYTk1ZS00Yzg3LWFmOTQtYjc2NmFkMTUxM2UzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA4MzIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmM2FlMGQ4MzQ1YmI5OGEzZDE2YTA2NTcxZjZhZDI3ODliNWIyMmU1YTFjMTU5MzgyN2E5ZGMxZjVlYzRkYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.10oxMYM4JvFeFHqbef4pCJd98NA2-YQcRLjNtXLkCcA)

我号欧服的

**Comment by missile-xuan** [comment]
> > 不挂钩 <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/38873815/397644636-94773397-ac67-4b45-b627-964bab2d1142.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ2MzYtOTQ3NzMzOTctYWM2Ny00YjQ1LWI2MjctOTY0YmFiMmQxMTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDkzOTRjZjY5OTM2ZGQ0NWNmYzRlMjc2OGU2ZWMzZjEzOThmMDA2MWM1NjM5OTU3ZDY2ZjNlNmMxZGRkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HNItZ-tQ0VggZaloPBbvhZYnE6fgtEwvebsvYHEn7Nw">
> > 挂钩 <img alt="image" width="1183" src="https://private-user-images.githubusercontent.com/38873815/397644791-ef1c71cc-5820-4c12-b5a1-e67d62ee3414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ3OTEtZWYxYzcxY2MtNTgyMC00YzEyLWI1YTEtZTY3ZDYyZWUzNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MGJhMDE3ZTMwZDlhMTZjZDMyNGRkZTY4ZjgyZjhjZDQ1Y2JhM2YzZTY4NzYyOThkMWVmYjAzMzZhNjU1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vl_gvrbY5gwMjhMdWDqo2Xm9c4N6-dMSWCT1of-KFas">
> > 我的号试了下正常的 那有没有可能是 这次箱子出的船你全都没有啊
> 
> 我也找群友试过，似乎国服是正常的，但是亚服就不行 圣诞刚冲了100发怎么会啥都没有 ![7c659d43da9a9b1e6f64d0ca83c3af08](https://private-user-images.githubusercontent.com/21017431/397645852-a8eb114c-a95e-4c87-af94-b766ad1513e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODM4MjYsIm5iZiI6MTczNDY4MzUyNiwicGF0aCI6Ii8yMTAxNzQzMS8zOTc2NDU4NTItYThlYjExNGMtYTk1ZS00Yzg3LWFmOTQtYjc2NmFkMTUxM2UzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA4MzIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmM2FlMGQ4MzQ1YmI5OGEzZDE2YTA2NTcxZjZhZDI3ODliNWIyMmU1YTFjMTU5MzgyN2E5ZGMxZjVlYzRkYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.10oxMYM4JvFeFHqbef4pCJd98NA2-YQcRLjNtXLkCcA)

奥  我知道了 那是因为没记录   这边只能记录你开过的船  刚开出来的没入库算不进去   没辙

**Comment by SnowMoonSS** [comment]
> > > 不挂钩 <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/38873815/397644636-94773397-ac67-4b45-b627-964bab2d1142.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ2MzYtOTQ3NzMzOTctYWM2Ny00YjQ1LWI2MjctOTY0YmFiMmQxMTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDkzOTRjZjY5OTM2ZGQ0NWNmYzRlMjc2OGU2ZWMzZjEzOThmMDA2MWM1NjM5OTU3ZDY2ZjNlNmMxZGRkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HNItZ-tQ0VggZaloPBbvhZYnE6fgtEwvebsvYHEn7Nw">
> > > 挂钩 <img alt="image" width="1183" src="https://private-user-images.githubusercontent.com/38873815/397644791-ef1c71cc-5820-4c12-b5a1-e67d62ee3414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzg0MzgsIm5iZiI6MTczNDY3ODEzOCwicGF0aCI6Ii8zODg3MzgxNS8zOTc2NDQ3OTEtZWYxYzcxY2MtNTgyMC00YzEyLWI1YTEtZTY3ZDYyZWUzNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MGJhMDE3ZTMwZDlhMTZjZDMyNGRkZTY4ZjgyZjhjZDQ1Y2JhM2YzZTY4NzYyOThkMWVmYjAzMzZhNjU1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vl_gvrbY5gwMjhMdWDqo2Xm9c4N6-dMSWCT1of-KFas">
> > > 我的号试了下正常的 那有没有可能是 这次箱子出的船你全都没有啊
> > 
> > 
> > 我也找群友试过，似乎国服是正常的，但是亚服就不行 圣诞刚冲了100发怎么会啥都没有 
> 
> 奥 我知道了 那是因为没记录 这边只能记录你开过的船 刚开出来的没入库算不进去 没辙

原来是这样……wws me sd都是正常的，这个居然只算开过的……
